### ISSUE TITLE
PAL support

### ISSUE THREAD

**Issue by superctr** [Shaw02/nsdlib#5]
**Is your feature request related to a problem? Please describe.**
When running this library on a PAL system, the music plays too slow and the pitch is incorrect.

**Describe the solution you'd like**
- Tempo should be adjusted (the base tempo should be 125 instead of 150)
- APU Frequency table should be adjusted for PAL clock (1.662607MHz PAL according to [Nesdev wiki](http://wiki.nesdev.com/w/index.php/APU#Pulse_.28.244000-4007.29))
- Although it would be nice to be able to detect the video mode (using [this method](https://github.com/pinobatch/pently/blob/master/sfxed/src/paldetect.s)), a compile switch would be enough.
- Perhaps sequence data would need to be adjusted (for the portamento command)
- Option to create PAL NSF files in `nsc` would also be nice.

**Comment by Shaw02** [comment]
### English
I would like to infrom that I have made the "nsd_pal.bin" and "nsd_pal.lib".
This binary and library is for PAL system.

- Branch: https://github.com/Shaw02/nsdlib/tree/feature/Support_PAL

However, I can not check it with the actual machine because I have no NES and TV for PAL.
If you have actual machine, I am happy that if you could check this library with the actual machine.

Thanks and best regards,

### 日本語
PAL用のバイナリ「nsd_pal.bin」及び、ライブラリ「nsd_pal.lib」を作成しました。

- ブランチ: https://github.com/Shaw02/nsdlib/tree/feature/Support_PAL

但し、実機環境を所有していないため、実機での動作確認はしておりません。
もし、実機環境を所有しておられましたら、ご確認いただければ幸いです。

以上、よろしくお願いいたします。

**Comment by Shaw02** [comment]
I've merged to develop branch.
Thank you.
